// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyyeavocabbrrxthsgxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5eWVhdm9jYWJicnJ4dGhzZ3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjg5MDIsImV4cCI6MjA2ODk0NDkwMn0.84HEPru9WgKbhkB8LEV3ncGpqwHvSZUG9olS1y8LY0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});